install apache-opennlp
install homebrew/dupes/apple-gcc42
install awscli
install caskroom/cask/brew-cask
install cabal-install
install ccrypt
install cloog
install direnv
install elixir
install erlang
install exif
install gcc
install gh
install git
install homebrew/versions/glfw3
install glib
install htop-osx
install hub
install imagemagick
install jq
install ncdu
install nmap
install node
install ossp-uuid
install packer
install pgcli
install postgresql
install rabbitmq
install rbenv
install thoughtbot/formulae/rcm
install redis
install ruby-build
install rust
install sqlite
install the_silver_searcher
install tig
install tree
install vim
